$(window).load(function(){$('#brandcarousal').carouFredSel({width:'100%',scroll:1,auto:!1,prev:'#prev',next:'#next',mousewheel:!0,swipe:{onMouse:!0,onTouch:!0}})});$('document').ready(function(){$('.tooltip-test').tooltip()
$('.popover-test').popover()
var $acdata=$('.accrodian-data'),$acclick=$('.accrodian-trigger');$acdata.hide();$acclick.first().addClass('active').next().show();$acclick.on('click',function(e){if($(this).next().is(':hidden')){$acclick.removeClass('active').next().slideUp(300);$(this).toggleClass('active').next().slideDown(300)}
e.preventDefault()});$('.togglehandle').click(function()
{$(this).toggleClass('active')
$(this).next('.toggledata').slideToggle()});$('.dropdown').hover(function(){$(this).addClass('open')},function(){$(this).removeClass('open')});$('.thumbnail').each(function()
{$(this).hover(function(){$(this).children('.shortlinks').fadeIn()},function(){$(this).children('.shortlinks').fadeOut()})});$('.checkoutsteptitle').addClass('down').next('.checkoutstep').fadeIn()
$('.checkoutsteptitle').live('click',function()
{$("select, input:checkbox, input:radio, input:file").css('display','blcok');$(this).toggleClass('down').next('.checkoutstep').slideToggle()});$("<select />").appendTo("nav.subnav");$("<option />",{"selected":"selected","value":"","text":"Go to..."}).appendTo("nav.subnav select");$("nav.subnav a[href]").each(function(){var el=$(this);$("<option />",{"value":el.attr("href"),"text":el.text()}).appendTo("nav.subnav select")});$("nav.subnav select").change(function(){window.location=$(this).find("option:selected").val()});$('.mainimage li #wrap').hide()
$('.mainimage li #wrap').eq(0).fadeIn()
$('ul.mainimage li.producthtumb').click(function(){var thumbindex=$(this).index()
$('.mainimage li #wrap').fadeOut(0)
$('.mainimage li #wrap').eq(thumbindex).fadeIn()
$('.cloud-zoom, .cloud-zoom-gallery').CloudZoom()})
$('#list').click(function()
{$(this).addClass('btn-orange').children('i').addClass('icon-white')
$('.grid').fadeOut()
$('.list').fadeIn()
$('#grid').removeClass('btn-orange').children('i').removeClass('icon-white')});$('#grid').click(function()
{$(this).addClass('btn-orange').children('i').addClass('icon-white')
$('.list').fadeOut()
$('.grid').fadeIn()
$('#list').removeClass('btn-orange').children('i').removeClass('icon-white')});$('#myTab a:first').tab('show')
$('#myTab a').click(function(e){e.preventDefault();$(this).tab('show')});$('.clostalert').click(function()
{$(this).parent('.alert').fadeOut()});$("#mainslider2").carouFredSel({responsive:!0,items:1,scroll:{fx:"crossfade"},auto:!1,mousewheel:!0,swipe:{onMouse:!0,onTouch:!0},pagination:{container:"#mainslider2_pag",anchorBuilder:function(nr){var src=$("img",this).attr("src");return'<img src="'+src+'" style="width:100px" />'}}});$(function(){$('#mainslider3').carouFredSel({responsive:!0,auto:!0,height:'100%',direction:'left',items:1,swipe:{onMouse:!0,onTouch:!0},scroll:{duration:1000,onBefore:function(data){data.items.visible.children().css('opacity',0).delay(200).fadeTo(400,1);data.items.old.children().fadeTo(400,0)}}})});$(window).load(function(){$('#carouseindex4').flexslider({animation:"slide",controlNav:!1,animationLoop:!1,slideshow:!1,itemWidth:226,asNavFor:'#sliderindex4'});$('#sliderindex4').flexslider({animation:"slide",controlNav:!1,animationLoop:!1,slideshow:!1,sync:"#carouseindex4"})});function prevTimers(){return allTimers().slice(0,$('.sliderindex5pager a.selected').index())}
function allTimers(){return $('.sliderindex5pager a span')}
$(function(){$('#sliderindex5').carouFredSel({items:1,responsive:!0,auto:{pauseOnHover:'resume',progress:{bar:'.sliderindex5pager a:first span'}},scroll:{fx:'crossfade',duration:300,timeoutDuration:2000,onAfter:function(){allTimers().stop().width(0);$(this).trigger('configuration',['auto.progress.bar','.sliderindex5pager a.selected span'])}},pagination:{container:'.sliderindex5pager',anchorBuilder:!1}})});$(function(){$('#mainslider6').carouFredSel({direction:'up',items:1,prev:'#prevmainslider6',next:'#nextmainslider6',pagination:"#pagermainslider6",mousewheel:!0,swipe:{onMouse:!0,onTouch:!0}})});$("#twitter").tweet({join_text:"auto",username:"pxcreate",modpath:'./twitter/',avatar_size:32,count:3,auto_join_text_default:"we said,",auto_join_text_ed:"we",auto_join_text_ing:"we were",auto_join_text_reply:"we replied",auto_join_text_url:"we were checking out",loading_text:"loading tweets..."})})
$(document).ready(function(){$(".contactform").validate({submitHandler:function(form){var name=$("input#name").val();var email=$("input#email").val();var url=$("input#url").val();var message=$("textarea#message").val();var dataString='name='+name+'&email='+email+'&url='+url+'&message='+message;$.ajax({type:"POST",url:"email.php",data:dataString,success:function(){$('#contactmsg').remove();$('.contactform').prepend("<div id='contactmsg' class='successmsg'>Form submitted successfully!</div>");$('#contactmsg').delay(1500).fadeOut(500);$('#submit_id').attr('disabled','disabled')}});return!1}})});$(window).load(function(){$("a.fancyboxpopup").fancybox().each(function(){$(this).append('<span class="viewfancypopup">&nbsp;</span>')});$('#mainslider').flexslider({animation:"slide",start:function(slider){$('body').removeClass('loading')}});$('#mainsliderside').flexslider({animation:"slide",start:function(slider){$('body').removeClass('loading')}});$('#catergoryslider').flexslider({animation:"slide",start:function(slider){$('body').removeClass('loading')}});$('#advertise').flexslider({animation:"fade",start:function(slider){$('body').removeClass('loading')}});$('#blogslider').flexslider({animation:"fade",start:function(slider){$('body').removeClass('loading')}});$('#musthave').flexslider({animation:"fade",start:function(slider){$('body').removeClass('loading')}});$('#testimonialsidebar').flexslider({animation:"slide",start:function(slider){$('body').removeClass('loading')}});$('#portfolioslider').flexslider({animation:"slide",start:function(slider){$('body').removeClass('loading')}})});$(window).scroll(function(){if($(this).scrollTop()>50){$('#gotop').fadeIn(500)}else{$('#gotop').fadeOut(500)}});$(window).load(function(){$.Isotope.prototype._getCenteredMasonryColumns=function(){this.width=this.element.width();var parentWidth=this.element.parent().width();var colW=this.options.masonry&&this.options.masonry.columnWidth||this.$filteredAtoms.outerWidth(!0)||parentWidth;var cols=Math.floor(parentWidth/colW);cols=Math.max(cols,1);this.masonry.cols=cols;this.masonry.columnWidth=colW};$.Isotope.prototype._masonryReset=function(){this.masonry={};this._getCenteredMasonryColumns();var i=this.masonry.cols;this.masonry.colYs=[];while(i--){this.masonry.colYs.push(0)}};$.Isotope.prototype._masonryResizeChanged=function(){var prevColCount=this.masonry.cols;this._getCenteredMasonryColumns();return(this.masonry.cols!==prevColCount)};$.Isotope.prototype._masonryGetContainerSize=function(){var unusedCols=0,i=this.masonry.cols;while(--i){if(this.masonry.colYs[i]!==0){break}
unusedCols++}
return{height:Math.max.apply(Math,this.masonry.colYs),width:(this.masonry.cols-unusedCols)*this.masonry.columnWidth}};$(function(){var $container=$('#portfoliocontainer');$container.find('.element').each(function(){var $this=$(this),number=parseInt($this.find('.number').text(),10);if(number%7%2===1){$this.addClass('width2')}
if(number%3===0){$this.addClass('height2')}});$container.isotope({itemSelector:'.element',masonry:{columnWidth:10},getSortData:{symbol:function($elem){return $elem.attr('data-symbol')},category:function($elem){return $elem.attr('data-category')},number:function($elem){return parseInt($elem.find('.number').text(),10)},weight:function($elem){return parseFloat($elem.find('.weight').text().replace(/[\(\)]/g,''))},name:function($elem){return $elem.find('.name').text()}}});var $optionSets=$('#options .option-set'),$optionLinks=$optionSets.find('a');$optionLinks.click(function(){var $this=$(this);if($this.hasClass('selected')){return!1}
var $optionSet=$this.parents('.option-set');$optionSet.find('.selected').removeClass('selected');$this.addClass('selected');var options={},key=$optionSet.attr('data-option-key'),value=$this.attr('data-option-value');value=value==='false'?!1:value;options[key]=value;if(key==='layoutMode'&&typeof changeLayoutMode==='function'){changeLayoutMode($this,options)}else{$container.isotope(options)}
return!1})})})